### ISSUE TITLE
How can I fix this error?

### ISSUE THREAD

**Issue by akan539** [MichaelChaoLi-cpu/GWPR.light#4]
Thank you for the amazing package "GWPR.lihgt"

But with my own data, I just encountered this error.. I have been trying different upperration and power of distance. It returns same results.. Would that be related with missing value? then How do I treat this issue?

Thanks 
![error_2023-06-09 152218](https://github.com/MichaelChaoLi-cpu/GWPR.light/assets/136057309/9f009f1b-d573-41b3-91c6-021eb157dd6a)

**Comment by MichaelChaoLi-cpu** [comment]
Sorry for the poor design of AIC approach. Can you change the approach to 'CV'? 
Please set 'p' to 2, also.

**Comment by akan539** [comment]
Thank you Micheal for your quick response! 
I didn't expect I would get a response from the developer this quick!! 
I appreciate it :)

But unfortunately with "CV", I encountered another error as attached.
My dataset is unbalanced panel, do you think it does matter?

Thanks in advance!

![error_2023-06-10 153408](https://github.com/MichaelChaoLi-cpu/GWPR.light/assets/136057309/db3d4279-b505-437a-ab8a-10692a3a391d)

**Comment by MichaelChaoLi-cpu** [comment]
It does not matter. `aim` is a dummy variable generated internally during calculation. We will release a new version within 3 months. In the new version, the issue would be solved. Now, I close this comment.
